-- DeSaga cu Legume: canonical schema for a fresh Supabase database.
-- Apply this on an empty/reset Supabase project before deploying the app.

begin;

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Enum types
-- ---------------------------------------------------------------------------

create type public.auth_event_type as enum (
  'REGISTER',
  'LOGIN',
  'LOGOUT',
  'SESSION_TIMEOUT',
  'USER_DELETED',
  'LOGIN_FAILED'
);

create type public.cart_status as enum (
  'ACTIVE',
  'CHECKED_OUT',
  'ABANDONED',
  'EXPIRED'
);

create type public.checkout_status as enum (
  'OPEN',
  'COMPLETED',
  'FAILED',
  'EXPIRED',
  'CANCELLED'
);

create type public.conversation_status as enum (
  'OPEN',
  'CLOSED',
  'ARCHIVED'
);

create type public.fulfillment_status as enum (
  'UNFULFILLED',
  'PARTIALLY_FULFILLED',
  'FULFILLED',
  'RETURNED'
);

create type public.inventory_movement_type as enum (
  'IN',
  'OUT',
  'ADJUSTMENT'
);

create type public.message_sender_type as enum (
  'USER',
  'ADMIN',
  'SYSTEM'
);

create type public.order_status as enum (
  'PENDING',
  'PLACED',
  'PAID',
  'PROCESSING',
  'SHIPPED',
  'DELIVERED',
  'COMPLETED',
  'CANCELLED',
  'REFUNDED'
);

create type public.payment_method_type as enum (
  'CARD',
  'BANK_TRANSFER',
  'CASH_ON_DELIVERY',
  'WALLET'
);

create type public.payment_status as enum (
  'PENDING',
  'AUTHORIZED',
  'PAID',
  'FAILED',
  'REFUNDED',
  'PARTIALLY_REFUNDED',
  'CANCELLED'
);

create type public.product_status as enum (
  'DRAFT',
  'ACTIVE',
  'OUT_OF_STOCK',
  'DISCONTINUED'
);

create type public.role_name as enum (
  'USER',
  'ADMIN'
);

create type public.session_status as enum (
  'ACTIVE',
  'LOGGED_OUT',
  'TIMED_OUT',
  'REVOKED'
);

create type public.user_status as enum (
  'ACTIVE',
  'LOCKED',
  'DELETED'
);

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table public.users (
  user_id bigint generated by default as identity primary key,
  user_uuid uuid not null default gen_random_uuid() unique,
  username varchar(80) not null unique,
  email varchar(255) not null unique,
  password_hash text not null,
  status public.user_status not null default 'ACTIVE',
  full_name text,
  phone varchar(50),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint users_deleted_state_check check (
    (status = 'DELETED' and deleted_at is not null)
    or (status <> 'DELETED' and deleted_at is null)
  ),
  constraint users_password_hash_format_check check (
    password_hash like 'scrypt:v1:%'
    or password_hash ~ '^[a-f0-9]{32}:[a-f0-9]{128}$'
  )
);

create table public.roles (
  role_id smallint generated by default as identity primary key,
  role_name public.role_name not null unique,
  description text
);

create table public.user_roles (
  user_id bigint not null references public.users(user_id) on update cascade on delete cascade,
  role_id smallint not null references public.roles(role_id) on update cascade on delete restrict,
  assigned_at timestamptz not null default now(),
  primary key (user_id, role_id)
);

create sequence public.order_number_seq
  as bigint
  start with 1
  increment by 1
  no minvalue
  no maxvalue
  cache 1;

create table public.sessions (
  session_id uuid primary key default gen_random_uuid(),
  user_id bigint not null references public.users(user_id) on update cascade on delete restrict,
  session_token_hash text not null unique,
  status public.session_status not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  last_activity_at timestamptz not null default now(),
  expires_at timestamptz not null,
  ended_at timestamptz,
  ip_address inet,
  user_agent text,
  constraint sessions_expiry_check check (expires_at > created_at),
  constraint sessions_ended_at_check check (ended_at is null or ended_at >= created_at),
  constraint sessions_status_end_check check (
    (status = 'ACTIVE' and ended_at is null)
    or (status <> 'ACTIVE' and ended_at is not null)
  )
);

create table public.auth_logs (
  log_id bigint generated by default as identity primary key,
  user_id bigint references public.users(user_id) on update cascade on delete set null,
  session_id uuid references public.sessions(session_id) on update cascade on delete set null,
  event_type public.auth_event_type not null,
  event_time timestamptz not null default now(),
  ip_address inet,
  user_agent text,
  details jsonb not null default '{}'::jsonb
);

create table public.product_categories (
  category_id bigint generated by default as identity primary key,
  name varchar(100) not null unique,
  slug varchar(120) not null unique,
  description text,
  created_at timestamptz not null default now(),
  constraint product_categories_allowed_slug_check check (slug in ('legume', 'fructe', 'la-borcan'))
);

create table public.products (
  product_id bigint generated by default as identity primary key,
  category_id bigint references public.product_categories(category_id) on update cascade on delete set null,
  sku varchar(80) not null unique,
  name varchar(200) not null,
  slug varchar(220) not null unique,
  description text,
  price numeric(12, 2) not null check (price >= 0),
  currency_code varchar(3) not null default 'RON' check (btrim(currency_code) ~ '^[A-Z]{3}$'),
  stock_quantity integer not null default 0 check (stock_quantity >= 0),
  status public.product_status not null default 'DRAFT',
  image_url text,
  created_by_admin_id bigint references public.users(user_id) on update cascade on delete set null,
  updated_by_admin_id bigint references public.users(user_id) on update cascade on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint products_deleted_status_check check (
    deleted_at is null or status in ('DISCONTINUED', 'DRAFT')
  )
);

create table public.inventory_movements (
  movement_id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(product_id) on update cascade on delete cascade,
  movement_type public.inventory_movement_type not null,
  quantity integer not null check (quantity > 0),
  note text,
  created_by_admin_id bigint references public.users(user_id) on update cascade on delete set null,
  created_at timestamptz not null default now()
);

create table public.user_addresses (
  address_id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(user_id) on update cascade on delete cascade,
  label varchar(100),
  full_name varchar(150) not null,
  phone varchar(50),
  line1 varchar(255) not null,
  line2 varchar(255),
  city varchar(120) not null,
  state_region varchar(120),
  postal_code varchar(40) not null,
  country_code char(2) not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.carts (
  cart_id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(user_id) on update cascade on delete cascade,
  status public.cart_status not null default 'ACTIVE',
  currency_code varchar(3) not null default 'RON' check (btrim(currency_code) ~ '^[A-Z]{3}$'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz
);

create table public.cart_items (
  cart_item_id bigint generated by default as identity primary key,
  cart_id bigint not null references public.carts(cart_id) on update cascade on delete cascade,
  product_id bigint not null references public.products(product_id) on update cascade on delete restrict,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12, 2) not null check (unit_price >= 0),
  currency_code varchar(3) not null default 'RON' check (btrim(currency_code) ~ '^[A-Z]{3}$'),
  added_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.checkouts (
  checkout_id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(user_id) on update cascade on delete restrict,
  cart_id bigint references public.carts(cart_id) on update cascade on delete set null,
  status public.checkout_status not null default 'OPEN',
  billing_address_id bigint references public.user_addresses(address_id) on update cascade on delete set null,
  shipping_address_id bigint references public.user_addresses(address_id) on update cascade on delete set null,
  subtotal_amount numeric(12, 2) not null default 0 check (subtotal_amount >= 0),
  tax_amount numeric(12, 2) not null default 0 check (tax_amount >= 0),
  shipping_amount numeric(12, 2) not null default 0 check (shipping_amount >= 0),
  discount_amount numeric(12, 2) not null default 0 check (discount_amount >= 0),
  total_amount numeric(12, 2) not null default 0 check (total_amount >= 0),
  currency_code varchar(3) not null default 'RON' check (btrim(currency_code) ~ '^[A-Z]{3}$'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz,
  completed_at timestamptz
);

create table public.orders (
  order_id bigint generated by default as identity primary key,
  order_number varchar(40) not null unique,
  user_id bigint not null references public.users(user_id) on update cascade on delete restrict,
  checkout_id bigint references public.checkouts(checkout_id) on update cascade on delete set null,
  status public.order_status not null default 'PENDING',
  payment_status public.payment_status not null default 'PENDING',
  fulfillment_status public.fulfillment_status not null default 'UNFULFILLED',
  customer_email varchar(255) not null,
  customer_full_name varchar(150) not null,
  customer_phone varchar(50),
  billing_full_name varchar(150) not null,
  billing_line1 varchar(255) not null,
  billing_line2 varchar(255),
  billing_city varchar(120) not null,
  billing_state_region varchar(120),
  billing_postal_code varchar(40) not null,
  billing_country_code char(2) not null,
  shipping_full_name varchar(150) not null,
  shipping_line1 varchar(255) not null,
  shipping_line2 varchar(255),
  shipping_city varchar(120) not null,
  shipping_state_region varchar(120),
  shipping_postal_code varchar(40) not null,
  shipping_country_code char(2) not null,
  subtotal_amount numeric(12, 2) not null check (subtotal_amount >= 0),
  tax_amount numeric(12, 2) not null default 0 check (tax_amount >= 0),
  shipping_amount numeric(12, 2) not null default 0 check (shipping_amount >= 0),
  discount_amount numeric(12, 2) not null default 0 check (discount_amount >= 0),
  total_amount numeric(12, 2) not null check (total_amount >= 0),
  currency_code varchar(3) not null default 'RON' check (btrim(currency_code) ~ '^[A-Z]{3}$'),
  notes text,
  placed_at timestamptz,
  paid_at timestamptz,
  shipped_at timestamptz,
  delivered_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  idempotency_key uuid
);

create table public.order_items (
  order_item_id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(order_id) on update cascade on delete cascade,
  product_id bigint references public.products(product_id) on update cascade on delete set null,
  sku varchar(80) not null,
  product_name varchar(200) not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12, 2) not null check (unit_price >= 0),
  line_total numeric(12, 2) not null check (line_total >= 0),
  currency_code varchar(3) not null default 'RON' check (btrim(currency_code) ~ '^[A-Z]{3}$')
);

create table public.payments (
  payment_id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(order_id) on update cascade on delete cascade,
  payment_method public.payment_method_type not null,
  status public.payment_status not null default 'PENDING',
  transaction_reference varchar(120) unique,
  amount numeric(12, 2) not null check (amount >= 0),
  currency_code varchar(3) not null default 'RON' check (btrim(currency_code) ~ '^[A-Z]{3}$'),
  provider_name varchar(100),
  provider_payload jsonb not null default '{}'::jsonb,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.order_status_history (
  history_id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(order_id) on update cascade on delete cascade,
  old_status public.order_status,
  new_status public.order_status not null,
  changed_by_user_id bigint references public.users(user_id) on update cascade on delete set null,
  note text,
  changed_at timestamptz not null default now()
);

create table public.support_conversations (
  conversation_id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(user_id) on update cascade on delete cascade,
  status public.conversation_status not null default 'OPEN',
  subject varchar(200) not null,
  order_id bigint references public.orders(order_id) on update cascade on delete set null,
  topic varchar(40) not null default 'GENERAL',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  closed_at timestamptz,
  constraint support_conversations_topic_check check (
    topic in ('ORDER', 'DELIVERY', 'PAYMENT', 'PRODUCT_AVAILABILITY', 'RETURN', 'HORECA', 'GENERAL')
  )
);

create table public.support_messages (
  message_id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.support_conversations(conversation_id) on update cascade on delete cascade,
  sender_user_id bigint references public.users(user_id) on update cascade on delete set null,
  sender_type public.message_sender_type not null,
  message_body text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.events (
  id bigint generated always as identity primary key,
  title text not null,
  description text not null,
  date timestamptz not null,
  location text not null,
  event_type text not null default 'festival',
  image_url text,
  published boolean not null default false,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint events_type_check check (event_type in ('festival', 'piata', 'atelier')),
  constraint events_published_at_check check (
    (published = false and published_at is null)
    or (published = true and published_at is not null)
  )
);

create table public.horeca_requests (
  request_id bigint generated always as identity primary key,
  business_name varchar(140) not null,
  contact_name varchar(120) not null,
  phone varchar(30) not null,
  email varchar(120),
  business_type varchar(80),
  city varchar(90),
  address text,
  products_needed text not null,
  estimated_quantity text,
  frequency varchar(80),
  preferred_contact varchar(40) not null default 'phone',
  message text,
  status varchar(30) not null default 'NEW',
  admin_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint horeca_requests_status_check check (status in ('NEW', 'CONTACTED', 'OFFER_SENT', 'CLOSED'))
);

create table public.app_rate_limits (
  key text primary key,
  request_count integer not null default 0 check (request_count >= 0),
  reset_at timestamptz not null,
  updated_at timestamptz not null default now()
);

create table public.checkout_idempotency_keys (
  idempotency_key text not null,
  user_id bigint not null references public.users(user_id) on update cascade on delete cascade,
  order_id bigint not null references public.orders(order_id) on update cascade on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, idempotency_key)
);

create table public.security_events (
  event_id uuid primary key default gen_random_uuid(),
  event_type text not null check (event_type in ('DECOY_HIT', 'RATE_LIMIT', 'LOGIN_FAILED')),
  request_id uuid not null,
  route text not null check (char_length(route) <= 160),
  method text not null check (method ~ '^[A-Z]{1,12}$'),
  observed_ip text check (observed_ip is null or char_length(observed_ip) <= 64),
  user_agent text check (user_agent is null or char_length(user_agent) <= 240),
  frequency_count integer not null default 1 check (frequency_count >= 1),
  rate_limited boolean not null default false,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  seen_at timestamptz,
  request_fingerprint text check (request_fingerprint is null or request_fingerprint ~ '^[a-f0-9]{64}$'),
  observed_ip_hash text check (observed_ip_hash is null or observed_ip_hash ~ '^[a-f0-9]{64}$')
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

create index users_status_idx on public.users(status);
create index users_deleted_at_idx on public.users(deleted_at) where deleted_at is not null;
create index user_roles_role_id_idx on public.user_roles(role_id);
create index sessions_user_status_expires_idx on public.sessions(user_id, status, expires_at);
create index sessions_active_expires_idx on public.sessions(expires_at) where status = 'ACTIVE';
create index auth_logs_user_time_idx on public.auth_logs(user_id, event_time desc);
create index auth_logs_session_time_idx on public.auth_logs(session_id, event_time desc);
create index auth_logs_event_time_idx on public.auth_logs(event_type, event_time desc);
create index product_categories_slug_idx on public.product_categories(slug);
create index products_public_catalog_idx on public.products(category_id, status, created_at desc) where deleted_at is null;
create index products_status_idx on public.products(status) where deleted_at is null;
create index inventory_movements_product_time_idx on public.inventory_movements(product_id, created_at desc);
create index inventory_movements_admin_time_idx on public.inventory_movements(created_by_admin_id, created_at desc);
create index user_addresses_user_idx on public.user_addresses(user_id);
create index user_addresses_default_idx on public.user_addresses(user_id) where is_default;
create unique index uq_active_cart_per_user on public.carts(user_id) where status = 'ACTIVE';
create index carts_user_status_idx on public.carts(user_id, status);
create unique index uq_cart_product_once on public.cart_items(cart_id, product_id);
create index cart_items_product_idx on public.cart_items(product_id);
create index checkouts_user_status_idx on public.checkouts(user_id, status, created_at desc);
create index checkouts_cart_idx on public.checkouts(cart_id);
create index orders_user_created_idx on public.orders(user_id, created_at desc);
create index orders_status_created_idx on public.orders(status, created_at desc);
create index orders_checkout_idx on public.orders(checkout_id);
create unique index orders_user_id_idempotency_key_uidx on public.orders(user_id, idempotency_key) where idempotency_key is not null;
create index order_items_order_idx on public.order_items(order_id);
create index order_items_product_idx on public.order_items(product_id);
create index payments_order_idx on public.payments(order_id);
create index payments_status_idx on public.payments(status);
create index order_status_history_order_time_idx on public.order_status_history(order_id, changed_at desc);
create index support_conversations_user_updated_idx on public.support_conversations(user_id, updated_at desc);
create index support_conversations_status_updated_idx on public.support_conversations(status, updated_at desc);
create index support_conversations_topic_updated_idx on public.support_conversations(topic, updated_at desc);
create index support_messages_conversation_created_idx on public.support_messages(conversation_id, created_at);
create index support_messages_unread_idx on public.support_messages(conversation_id, sender_type, is_read);
create index events_date_idx on public.events(date);
create index events_public_date_idx on public.events(date) where published = true;
create index events_type_date_idx on public.events(event_type, date);
create index horeca_requests_status_created_idx on public.horeca_requests(status, created_at desc);
create index app_rate_limits_reset_idx on public.app_rate_limits(reset_at);
create index checkout_idempotency_keys_order_idx on public.checkout_idempotency_keys(order_id);
create index security_events_created_idx on public.security_events(created_at desc);
create index security_events_route_created_idx on public.security_events(route, created_at desc);
create index security_events_unseen_idx on public.security_events(created_at desc) where seen_at is null;
create index security_events_type_created_idx on public.security_events(event_type, created_at desc);
create index security_events_ip_hash_created_idx on public.security_events(observed_ip_hash, created_at desc) where observed_ip_hash is not null;
create index security_events_fingerprint_created_idx on public.security_events(request_fingerprint, created_at desc) where request_fingerprint is not null;

-- ---------------------------------------------------------------------------
-- Helpers and triggers
-- ---------------------------------------------------------------------------

create function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create function public.user_has_role(p_user_id bigint, p_role_name public.role_name)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.role_id = ur.role_id
    where ur.user_id = p_user_id
      and r.role_name = p_role_name
  );
$$;

create function public.is_admin(p_user_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select public.user_has_role(p_user_id, 'ADMIN'::public.role_name);
$$;

create function public.current_app_user_id()
returns bigint
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  with claims as (
    select auth.jwt() as jwt, auth.uid() as supabase_uid
  )
  select coalesce(
    case
      when (jwt ->> 'app_user_id') ~ '^[0-9]+$'
        then (jwt ->> 'app_user_id')::bigint
      else null
    end,
    (
      select u.user_id
      from public.users u
      where u.user_uuid = supabase_uid
      limit 1
    )
  )
  from claims;
$$;

create function public.current_app_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select public.is_admin(public.current_app_user_id());
$$;

create function public.grant_admin_role(p_user_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  admin_role_id smallint;
begin
  select role_id into admin_role_id from public.roles where role_name = 'ADMIN';
  if admin_role_id is null then
    raise exception 'Rolul ADMIN nu există.';
  end if;

  insert into public.user_roles(user_id, role_id)
  values (p_user_id, admin_role_id)
  on conflict do nothing;

  return true;
end;
$$;

create function public.revoke_admin_role(p_user_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  admin_role_id smallint;
begin
  select role_id into admin_role_id from public.roles where role_name = 'ADMIN';
  if admin_role_id is null then
    return false;
  end if;

  delete from public.user_roles
  where user_id = p_user_id
    and role_id = admin_role_id;

  return true;
end;
$$;

create function public.validate_user_is_customer()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if public.user_has_role(new.user_id, 'ADMIN'::public.role_name) then
    raise exception 'Administratorii nu pot folosi această resursă.';
  end if;
  return new;
end;
$$;

create function public.validate_product_admin_users()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if new.created_by_admin_id is not null and not public.user_has_role(new.created_by_admin_id, 'ADMIN'::public.role_name) then
    raise exception 'created_by_admin_id trebuie să aparțină unui administrator.';
  end if;

  if new.updated_by_admin_id is not null and not public.user_has_role(new.updated_by_admin_id, 'ADMIN'::public.role_name) then
    raise exception 'updated_by_admin_id trebuie să aparțină unui administrator.';
  end if;

  return new;
end;
$$;

create function public.prepare_cart_item()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
declare
  product_row public.products%rowtype;
begin
  select *
  into product_row
  from public.products
  where product_id = new.product_id
    and deleted_at is null;

  if not found then
    raise exception 'Product no longer exists.';
  end if;

  if product_row.status <> 'ACTIVE'::public.product_status then
    raise exception 'Product is not available.';
  end if;

  if product_row.stock_quantity < new.quantity then
    raise exception 'Insufficient stock for one or more products.';
  end if;

  new.unit_price = product_row.price;
  new.currency_code = product_row.currency_code;
  new.updated_at = now();
  return new;
end;
$$;

create function public.apply_inventory_movement()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if new.movement_type = 'IN'::public.inventory_movement_type then
    update public.products
    set stock_quantity = stock_quantity + new.quantity,
        status = case when status = 'OUT_OF_STOCK' then 'ACTIVE'::public.product_status else status end
    where product_id = new.product_id;
  elsif new.movement_type = 'OUT'::public.inventory_movement_type then
    update public.products
    set stock_quantity = stock_quantity - new.quantity
    where product_id = new.product_id
      and stock_quantity >= new.quantity;

    if not found then
      raise exception 'Insufficient stock for one or more products.';
    end if;
  end if;

  return new;
end;
$$;

create function public.log_order_status_change()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if current_setting('app.skip_order_status_history', true) = 'on' then
    return new;
  end if;

  if old.status is distinct from new.status then
    insert into public.order_status_history(order_id, old_status, new_status, changed_by_user_id, note)
    values (new.order_id, old.status, new.status, null, 'Schimbare automată de status.');
  end if;

  return new;
end;
$$;

create function public.sync_order_payment_status()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  update public.orders
  set payment_status = new.status,
      paid_at = case when new.status = 'PAID' then coalesce(new.paid_at, now()) else paid_at end
  where order_id = new.order_id;

  return new;
end;
$$;

create function public.prevent_auth_log_changes()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  raise exception 'Jurnalul de autentificare nu poate fi modificat.';
end;
$$;

create trigger set_updated_at_users before update on public.users for each row execute function public.set_updated_at();
create trigger set_updated_at_products before update on public.products for each row execute function public.set_updated_at();
create trigger set_updated_at_user_addresses before update on public.user_addresses for each row execute function public.set_updated_at();
create trigger set_updated_at_carts before update on public.carts for each row execute function public.set_updated_at();
create trigger set_updated_at_cart_items before update on public.cart_items for each row execute function public.set_updated_at();
create trigger set_updated_at_checkouts before update on public.checkouts for each row execute function public.set_updated_at();
create trigger set_updated_at_orders before update on public.orders for each row execute function public.set_updated_at();
create trigger set_updated_at_payments before update on public.payments for each row execute function public.set_updated_at();
create trigger set_updated_at_support_conversations before update on public.support_conversations for each row execute function public.set_updated_at();
create trigger set_updated_at_events before update on public.events for each row execute function public.set_updated_at();
create trigger set_updated_at_horeca_requests before update on public.horeca_requests for each row execute function public.set_updated_at();
create trigger set_updated_at_app_rate_limits before update on public.app_rate_limits for each row execute function public.set_updated_at();

create trigger trg_validate_cart_user before insert or update on public.carts for each row execute function public.validate_user_is_customer();
create trigger trg_validate_checkout_user before insert or update on public.checkouts for each row execute function public.validate_user_is_customer();
create trigger trg_validate_order_user before insert or update on public.orders for each row execute function public.validate_user_is_customer();
create trigger trg_validate_product_admin_users before insert or update on public.products for each row execute function public.validate_product_admin_users();
create trigger trg_prepare_cart_item before insert or update on public.cart_items for each row execute function public.prepare_cart_item();
create trigger trg_apply_inventory_movement after insert on public.inventory_movements for each row execute function public.apply_inventory_movement();
create trigger trg_log_order_status_change after update of status on public.orders for each row execute function public.log_order_status_change();
create trigger trg_sync_order_payment_status after insert or update of status on public.payments for each row execute function public.sync_order_payment_status();
create trigger trg_prevent_auth_log_update before update or delete on public.auth_logs for each row execute function public.prevent_auth_log_changes();

-- ---------------------------------------------------------------------------
-- RPC functions used by the application
-- ---------------------------------------------------------------------------

create function public.generate_order_number()
returns varchar(40)
language sql
volatile
set search_path = public, pg_temp
as $$
  select nextval('public.order_number_seq')::text::varchar(40);
$$;

create function public.resolve_session(p_token_hash text)
returns table (
  session_id uuid,
  user_id bigint,
  expires_at timestamptz,
  last_activity_at timestamptz,
  user_email varchar,
  username varchar,
  full_name text,
  phone varchar,
  user_status public.user_status,
  roles text[]
)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select
    s.session_id,
    u.user_id,
    s.expires_at,
    s.last_activity_at,
    u.email as user_email,
    u.username,
    u.full_name,
    u.phone,
    u.status as user_status,
    coalesce(array_agg(r.role_name::text order by r.role_name::text) filter (where r.role_name is not null), '{}'::text[]) as roles
  from public.sessions s
  join public.users u on u.user_id = s.user_id
  left join public.user_roles ur on ur.user_id = u.user_id
  left join public.roles r on r.role_id = ur.role_id
  where s.session_token_hash = p_token_hash
    and s.status = 'ACTIVE'
    and s.expires_at > now()
    and u.status = 'ACTIVE'
    and u.deleted_at is null
  group by s.session_id, u.user_id, s.expires_at, s.last_activity_at, u.email, u.username, u.full_name, u.phone, u.status
  limit 1;
$$;

create function public.consume_rate_limit(
  p_key text,
  p_limit integer,
  p_window_seconds integer
)
returns table (
  allowed boolean,
  remaining integer,
  retry_after_seconds integer
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_now timestamptz := now();
  v_reset_at timestamptz;
  v_count integer;
begin
  if p_key is null or btrim(p_key) = '' then
    raise exception 'Cheia de rate-limit este obligatorie.';
  end if;
  if p_limit < 1 or p_window_seconds < 1 then
    raise exception 'Configurare rate-limit invalidă.';
  end if;

  insert into public.app_rate_limits(key, request_count, reset_at, updated_at)
  values (left(p_key, 300), 1, v_now + make_interval(secs => p_window_seconds), v_now)
  on conflict (key) do update
    set request_count = case
          when public.app_rate_limits.reset_at <= v_now then 1
          else public.app_rate_limits.request_count + 1
        end,
        reset_at = case
          when public.app_rate_limits.reset_at <= v_now then v_now + make_interval(secs => p_window_seconds)
          else public.app_rate_limits.reset_at
        end,
        updated_at = v_now
  returning request_count, reset_at into v_count, v_reset_at;

  allowed := v_count <= p_limit;
  remaining := greatest(p_limit - v_count, 0);
  retry_after_seconds := case
    when allowed then 0
    else greatest(1, ceil(extract(epoch from (v_reset_at - v_now)))::integer)
  end;

  return next;
end;
$$;

create function public.replace_cart_items(p_user_id bigint, p_items jsonb)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  app_user public.users%rowtype;
  raw_item jsonb;
  parsed_product_id bigint;
  parsed_quantity integer;
  v_item_count integer;
  v_product_count integer;
  v_cart_id bigint;
  v_currency varchar(3);
begin
  perform pg_advisory_xact_lock(hashtextextended('cart:' || p_user_id::text, 0));

  select * into app_user
  from public.users
  where user_id = p_user_id
    and status = 'ACTIVE'
    and deleted_at is null;

  if not found then
    raise exception 'Utilizatorul nu este activ.';
  end if;

  if public.user_has_role(p_user_id, 'ADMIN'::public.role_name) then
    raise exception 'Administratorii nu pot avea coș.';
  end if;

  if p_items is null or jsonb_typeof(p_items) <> 'array' then
    raise exception 'Coșul trebuie să fie o listă de produse.';
  end if;

  drop table if exists pg_temp.cart_rpc_items;

  create temporary table cart_rpc_items (
    product_id bigint primary key,
    quantity integer not null check (quantity > 0 and quantity <= 99)
  ) on commit drop;

  for raw_item in select value from jsonb_array_elements(p_items) as item(value)
  loop
    if jsonb_typeof(raw_item) <> 'object'
      or coalesce(raw_item ->> 'product_id', raw_item ->> 'productId', '') !~ '^[0-9]+$'
      or coalesce(raw_item ->> 'quantity', '') !~ '^[0-9]+$' then
      raise exception 'Produs invalid în coș.';
    end if;

    parsed_product_id := coalesce(raw_item ->> 'product_id', raw_item ->> 'productId')::bigint;
    parsed_quantity := (raw_item ->> 'quantity')::integer;

    if parsed_quantity < 1 or parsed_quantity > 99 then
      raise exception 'Cantitatea trebuie să fie între 1 și 99.';
    end if;

    insert into cart_rpc_items(product_id, quantity)
    values (parsed_product_id, parsed_quantity)
    on conflict (product_id) do update
      set quantity = least(99, cart_rpc_items.quantity + excluded.quantity);
  end loop;

  select count(*) into v_item_count from cart_rpc_items;
  if v_item_count > 100 then
    raise exception 'Coșul nu poate conține peste 100 de produse distincte.';
  end if;

  select count(*), min(p.currency_code)
  into v_product_count, v_currency
  from cart_rpc_items i
  join public.products p on p.product_id = i.product_id
  where p.deleted_at is null
    and p.status = 'ACTIVE'
    and p.stock_quantity >= i.quantity;

  if v_product_count <> v_item_count then
    raise exception 'Un produs nu mai este disponibil sau nu are stoc suficient.';
  end if;

  select c.cart_id into v_cart_id
  from public.carts c
  where c.user_id = p_user_id
    and c.status = 'ACTIVE'
  order by c.cart_id desc
  limit 1
  for update;

  if v_cart_id is null then
    insert into public.carts(user_id, status, currency_code)
    values (p_user_id, 'ACTIVE', coalesce(v_currency, 'RON'))
    returning cart_id into v_cart_id;
  end if;

  delete from public.cart_items where cart_id = v_cart_id;

  insert into public.cart_items(cart_id, product_id, quantity)
  select v_cart_id, product_id, quantity
  from cart_rpc_items
  order by product_id;
end;
$$;

create function public.support_conversation_summaries(
  p_viewer_user_id bigint,
  p_is_admin boolean,
  p_status text default null,
  p_topic text default null,
  p_search text default null,
  p_limit integer default 30,
  p_offset integer default 0
)
returns table (
  conversation_id bigint,
  user_id bigint,
  subject varchar,
  status public.conversation_status,
  created_at timestamptz,
  updated_at timestamptz,
  closed_at timestamptz,
  order_id bigint,
  topic varchar,
  user_email varchar,
  username varchar,
  full_name text,
  phone varchar,
  order_number varchar,
  total_amount numeric,
  currency_code varchar,
  order_status public.order_status,
  payment_status public.payment_status,
  fulfillment_status public.fulfillment_status,
  order_created_at timestamptz,
  placed_at timestamptz,
  last_message_id bigint,
  last_message_body text,
  last_message_sender_type public.message_sender_type,
  last_message_created_at timestamptz,
  unread_count bigint,
  total_count bigint
)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  with filtered as (
    select
      sc.conversation_id,
      sc.user_id,
      sc.subject,
      sc.status,
      sc.created_at,
      sc.updated_at,
      sc.closed_at,
      sc.order_id,
      sc.topic,
      u.email as user_email,
      u.username,
      u.full_name,
      u.phone,
      o.order_number,
      o.total_amount,
      o.currency_code,
      o.status as order_status,
      o.payment_status,
      o.fulfillment_status,
      o.created_at as order_created_at,
      o.placed_at,
      lm.message_id as last_message_id,
      lm.message_body as last_message_body,
      lm.sender_type as last_message_sender_type,
      lm.created_at as last_message_created_at,
      (
        select count(*)
        from public.support_messages sm
        where sm.conversation_id = sc.conversation_id
          and sm.is_read = false
          and sm.sender_type = case when p_is_admin then 'USER'::public.message_sender_type else 'ADMIN'::public.message_sender_type end
      ) as unread_count
    from public.support_conversations sc
    join public.users u on u.user_id = sc.user_id
    left join public.orders o on o.order_id = sc.order_id
    left join lateral (
      select sm.message_id, sm.message_body, sm.sender_type, sm.created_at
      from public.support_messages sm
      where sm.conversation_id = sc.conversation_id
      order by sm.created_at desc, sm.message_id desc
      limit 1
    ) lm on true
    where (p_is_admin or sc.user_id = p_viewer_user_id)
      and (p_status is null or sc.status::text = upper(p_status))
      and (p_topic is null or sc.topic = upper(p_topic))
      and (
        nullif(btrim(coalesce(p_search, '')), '') is null
        or (
          sc.subject ilike '%' || p_search || '%'
          or u.email ilike '%' || p_search || '%'
          or u.username ilike '%' || p_search || '%'
          or coalesce(u.full_name, '') ilike '%' || p_search || '%'
          or coalesce(u.phone, '') ilike '%' || p_search || '%'
          or coalesce(o.order_number, '') ilike '%' || p_search || '%'
          or coalesce(lm.message_body, '') ilike '%' || p_search || '%'
        )
      )
  )
  select
    filtered.*,
    count(*) over() as total_count
  from filtered
  order by filtered.updated_at desc, filtered.conversation_id desc
  limit greatest(1, least(coalesce(p_limit, 30), 100))
  offset greatest(0, coalesce(p_offset, 0));
$$;

create function public.update_order_admin(
  p_order_id bigint,
  p_admin_user_id bigint default null,
  p_status text default null,
  p_payment_status text default null,
  p_fulfillment_status text default null,
  p_note text default null
)
returns table (
  order_id bigint,
  order_number varchar,
  user_id bigint,
  customer_full_name varchar,
  customer_email varchar,
  total_amount numeric,
  currency_code varchar,
  status public.order_status,
  payment_status public.payment_status,
  fulfillment_status public.fulfillment_status,
  created_at timestamptz,
  placed_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  existing public.orders%rowtype;
  next_status public.order_status;
  next_payment_status public.payment_status;
  next_fulfillment_status public.fulfillment_status;
begin
  select * into existing
  from public.orders o
  where o.order_id = p_order_id
  for update;

  if not found then
    raise exception 'Comanda nu a fost găsită.' using errcode = 'P0002';
  end if;

  if p_admin_user_id is not null and not public.user_has_role(p_admin_user_id, 'ADMIN'::public.role_name) then
    raise exception 'Utilizatorul nu este administrator.';
  end if;

  next_status := coalesce(upper(nullif(btrim(p_status), ''))::public.order_status, existing.status);
  next_payment_status := coalesce(upper(nullif(btrim(p_payment_status), ''))::public.payment_status, existing.payment_status);
  next_fulfillment_status := coalesce(upper(nullif(btrim(p_fulfillment_status), ''))::public.fulfillment_status, existing.fulfillment_status);

  perform set_config('app.skip_order_status_history', 'on', true);

  update public.orders o
  set status = next_status,
      payment_status = next_payment_status,
      fulfillment_status = next_fulfillment_status,
      paid_at = case when next_payment_status = 'PAID' then coalesce(o.paid_at, now()) else o.paid_at end,
      shipped_at = case when next_status = 'SHIPPED' then coalesce(o.shipped_at, now()) else o.shipped_at end,
      delivered_at = case when next_status in ('DELIVERED', 'COMPLETED') then coalesce(o.delivered_at, now()) else o.delivered_at end,
      cancelled_at = case when next_status = 'CANCELLED' then coalesce(o.cancelled_at, now()) else o.cancelled_at end
  where o.order_id = p_order_id;

  if existing.status is distinct from next_status then
    insert into public.order_status_history(order_id, old_status, new_status, changed_by_user_id, note)
    values (
      p_order_id,
      existing.status,
      next_status,
      p_admin_user_id,
      nullif(btrim(coalesce(p_note, '')), '')
    );
  end if;

  return query
  select
    o.order_id,
    o.order_number,
    o.user_id,
    o.customer_full_name,
    o.customer_email,
    o.total_amount,
    o.currency_code,
    o.status,
    o.payment_status,
    o.fulfillment_status,
    o.created_at,
    o.placed_at
  from public.orders o
  where o.order_id = p_order_id;
end;
$$;

create function public.place_order(
  p_user_id bigint,
  p_items jsonb,
  p_full_name text,
  p_phone text,
  p_delivery_method text default 'pickup',
  p_payment_method public.payment_method_type default 'CASH_ON_DELIVERY',
  p_address_line1 text default null,
  p_address_line2 text default null,
  p_city text default null,
  p_state_region text default null,
  p_postal_code text default null,
  p_country_code text default 'RO',
  p_customer_message text default null,
  p_idempotency_key uuid default null
)
returns table (
  order_id bigint,
  order_number varchar(40),
  status public.order_status,
  payment_status public.payment_status,
  fulfillment_status public.fulfillment_status,
  total_amount numeric(12, 2),
  currency_code varchar(3),
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  app_user public.users%rowtype;
  raw_item jsonb;
  raw_product_id text;
  raw_quantity text;
  parsed_product_id bigint;
  parsed_quantity integer;
  v_item_count integer;
  v_product_count integer := 0;
  locked_product record;
  existing_order_id bigint;
  v_cart_id bigint;
  v_billing_address_id bigint;
  v_shipping_address_id bigint;
  v_checkout_id bigint;
  v_support_conversation_id bigint;
  v_order_id bigint;
  v_order_number varchar(40);
  v_delivery_method text;
  v_full_name text;
  v_phone text;
  v_country_code_text text;
  v_country_code char(2);
  v_billing_line1 text;
  v_billing_line2 text;
  v_billing_city text;
  v_billing_state_region text;
  v_billing_postal_code text;
  v_shipping_line1 text;
  v_shipping_line2 text;
  v_shipping_city text;
  v_shipping_state_region text;
  v_shipping_postal_code text;
  v_currency varchar(3);
  v_subtotal numeric(12, 2) := 0;
  v_tax_amount numeric(12, 2) := 0;
  v_shipping_amount numeric(12, 2) := 0;
  v_discount_amount numeric(12, 2) := 0;
  v_total_amount numeric(12, 2) := 0;
begin
  if p_idempotency_key is not null then
    perform pg_advisory_xact_lock(hashtextextended(p_user_id::text || ':' || p_idempotency_key::text, 0));

    select cik.order_id into existing_order_id
    from public.checkout_idempotency_keys cik
    where cik.user_id = p_user_id
      and cik.idempotency_key = p_idempotency_key::text;

    if existing_order_id is not null then
      return query
      select o.order_id, o.order_number, o.status, o.payment_status, o.fulfillment_status, o.total_amount, o.currency_code, o.created_at
      from public.orders o
      where o.order_id = existing_order_id;
      return;
    end if;
  end if;

  select * into app_user
  from public.users u
  where u.user_id = p_user_id
    and u.status = 'ACTIVE'
    and u.deleted_at is null;

  if not found then
    raise exception 'Checkout requires an active user.';
  end if;

  if public.user_has_role(p_user_id, 'ADMIN'::public.role_name) then
    raise exception 'Admins cannot place orders.';
  end if;

  v_full_name := nullif(btrim(coalesce(p_full_name, '')), '');
  v_phone := nullif(btrim(coalesce(p_phone, '')), '');
  v_delivery_method := lower(coalesce(nullif(btrim(coalesce(p_delivery_method, '')), ''), 'pickup'));
  v_country_code_text := upper(coalesce(nullif(btrim(coalesce(p_country_code, '')), ''), 'RO'));

  if v_full_name is null then
    raise exception 'Full name is required.';
  end if;
  if v_phone is null then
    raise exception 'Phone is required.';
  end if;
  if v_delivery_method not in ('pickup', 'delivery') then
    raise exception 'Delivery method is invalid.';
  end if;
  if v_country_code_text !~ '^[A-Z]{2}$' then
    raise exception 'Country code is invalid.';
  end if;

  v_country_code := v_country_code_text::char(2);

  if p_items is null or jsonb_typeof(p_items) <> 'array' then
    raise exception 'Checkout items must be a JSON array.';
  end if;

  drop table if exists pg_temp.checkout_rpc_items;
  drop table if exists pg_temp.checkout_rpc_products;

  create temporary table checkout_rpc_items (
    product_id bigint primary key,
    quantity integer not null check (quantity > 0 and quantity <= 99)
  ) on commit drop;

  create temporary table checkout_rpc_products (
    product_id bigint primary key,
    sku varchar(80) not null,
    product_name varchar(200) not null,
    quantity integer not null,
    unit_price numeric(12, 2) not null,
    line_total numeric(12, 2) not null,
    currency_code varchar(3) not null
  ) on commit drop;

  for raw_item in select value from jsonb_array_elements(p_items) as item(value)
  loop
    if jsonb_typeof(raw_item) <> 'object' then
      raise exception 'Invalid checkout item payload.';
    end if;

    raw_product_id := coalesce(raw_item ->> 'productId', raw_item ->> 'product_id');
    raw_quantity := raw_item ->> 'quantity';

    if raw_product_id is null or raw_product_id !~ '^[0-9]+$' or raw_quantity is null or raw_quantity !~ '^[0-9]+$' then
      raise exception 'Invalid checkout item payload.';
    end if;

    parsed_product_id := raw_product_id::bigint;
    parsed_quantity := raw_quantity::integer;

    if parsed_quantity < 1 or parsed_quantity > 99 then
      raise exception 'Item quantity must be between 1 and 99.';
    end if;

    insert into checkout_rpc_items(product_id, quantity)
    values (parsed_product_id, parsed_quantity)
    on conflict (product_id) do update
      set quantity = least(99, checkout_rpc_items.quantity + excluded.quantity);
  end loop;

  select count(*) into v_item_count from checkout_rpc_items;
  if v_item_count = 0 then
    raise exception 'Checkout requires at least one item.';
  end if;
  if v_item_count > 100 then
    raise exception 'Checkout cannot contain more than 100 distinct products.';
  end if;

  for locked_product in
    select p.product_id, p.sku, p.name, p.price, p.currency_code, p.stock_quantity, p.status, i.quantity
    from checkout_rpc_items i
    join public.products p on p.product_id = i.product_id
    where p.deleted_at is null
    order by p.product_id
    for update of p
  loop
    v_product_count := v_product_count + 1;

    if locked_product.status <> 'ACTIVE'::public.product_status then
      raise exception 'Product is not available.';
    end if;
    if locked_product.stock_quantity < locked_product.quantity then
      raise exception 'Insufficient stock for one or more products.';
    end if;

    if v_currency is null then
      v_currency := locked_product.currency_code;
    elsif v_currency <> locked_product.currency_code then
      raise exception 'Mixed currency checkout is not supported.';
    end if;

    insert into checkout_rpc_products(product_id, sku, product_name, quantity, unit_price, line_total, currency_code)
    values (
      locked_product.product_id,
      locked_product.sku,
      locked_product.name,
      locked_product.quantity,
      locked_product.price,
      locked_product.price * locked_product.quantity,
      locked_product.currency_code
    );
  end loop;

  if v_product_count <> v_item_count then
    raise exception 'Product no longer exists.';
  end if;

  select coalesce(sum(rp.line_total), 0)::numeric(12, 2) into v_subtotal
  from checkout_rpc_products rp;
  v_currency := coalesce(v_currency, 'RON');
  if v_delivery_method = 'delivery' then
    v_shipping_amount := case when v_subtotal >= 150 then 0 else 20 end;
  end if;
  v_total_amount := v_subtotal + v_shipping_amount + v_tax_amount - v_discount_amount;

  if v_delivery_method = 'pickup' then
    v_billing_line1 := 'Ridicare din rulota DeSaga';
    v_billing_line2 := null;
    v_billing_city := 'Cluj-Napoca';
    v_billing_state_region := 'Cluj';
    v_billing_postal_code := '400000';
    v_shipping_line1 := v_billing_line1;
    v_shipping_line2 := null;
    v_shipping_city := v_billing_city;
    v_shipping_state_region := v_billing_state_region;
    v_shipping_postal_code := v_billing_postal_code;
  else
    v_billing_line1 := nullif(btrim(coalesce(p_address_line1, '')), '');
    v_billing_line2 := nullif(btrim(coalesce(p_address_line2, '')), '');
    v_billing_city := nullif(btrim(coalesce(p_city, '')), '');
    v_billing_state_region := nullif(btrim(coalesce(p_state_region, '')), '');
    v_billing_postal_code := nullif(btrim(coalesce(p_postal_code, '')), '');

    if v_billing_line1 is null or v_billing_city is null or v_billing_postal_code is null then
      raise exception 'Delivery address is incomplete.';
    end if;

    v_shipping_line1 := v_billing_line1;
    v_shipping_line2 := v_billing_line2;
    v_shipping_city := v_billing_city;
    v_shipping_state_region := v_billing_state_region;
    v_shipping_postal_code := v_billing_postal_code;
  end if;

  select c.cart_id into v_cart_id
  from public.carts c
  where c.user_id = p_user_id and c.status = 'ACTIVE'
  order by c.cart_id desc
  limit 1
  for update;

  if v_cart_id is null then
    insert into public.carts(user_id, status, currency_code)
    values (p_user_id, 'ACTIVE', v_currency)
    returning cart_id into v_cart_id;
  end if;

  delete from public.cart_items where cart_id = v_cart_id;
  insert into public.cart_items(cart_id, product_id, quantity)
  select v_cart_id, rp.product_id, rp.quantity
  from checkout_rpc_products rp
  order by rp.product_id;

  insert into public.user_addresses(user_id, label, full_name, phone, line1, line2, city, state_region, postal_code, country_code, is_default)
  values (p_user_id, 'Facturare', v_full_name, v_phone, v_billing_line1, v_billing_line2, v_billing_city, v_billing_state_region, v_billing_postal_code, v_country_code, false)
  returning address_id into v_billing_address_id;

  insert into public.user_addresses(user_id, label, full_name, phone, line1, line2, city, state_region, postal_code, country_code, is_default)
  values (p_user_id, case when v_delivery_method = 'delivery' then 'Livrare' else 'Ridicare' end, v_full_name, v_phone, v_shipping_line1, v_shipping_line2, v_shipping_city, v_shipping_state_region, v_shipping_postal_code, v_country_code, false)
  returning address_id into v_shipping_address_id;

  insert into public.checkouts(user_id, cart_id, status, billing_address_id, shipping_address_id, subtotal_amount, tax_amount, shipping_amount, discount_amount, total_amount, currency_code, completed_at)
  values (p_user_id, v_cart_id, 'COMPLETED', v_billing_address_id, v_shipping_address_id, v_subtotal, v_tax_amount, v_shipping_amount, v_discount_amount, v_total_amount, v_currency, now())
  returning checkout_id into v_checkout_id;

  v_order_number := public.generate_order_number();

  insert into public.orders(
    order_number, user_id, checkout_id, status, payment_status, fulfillment_status,
    customer_email, customer_full_name, customer_phone,
    billing_full_name, billing_line1, billing_line2, billing_city, billing_state_region, billing_postal_code, billing_country_code,
    shipping_full_name, shipping_line1, shipping_line2, shipping_city, shipping_state_region, shipping_postal_code, shipping_country_code,
    subtotal_amount, tax_amount, shipping_amount, discount_amount, total_amount, currency_code, notes, placed_at, idempotency_key
  )
  values (
    v_order_number, p_user_id, v_checkout_id, 'PLACED', 'PENDING', 'UNFULFILLED',
    app_user.email, v_full_name, v_phone,
    v_full_name, v_billing_line1, v_billing_line2, v_billing_city, v_billing_state_region, v_billing_postal_code, v_country_code,
    v_full_name, v_shipping_line1, v_shipping_line2, v_shipping_city, v_shipping_state_region, v_shipping_postal_code, v_country_code,
    v_subtotal, v_tax_amount, v_shipping_amount, v_discount_amount, v_total_amount, v_currency, nullif(btrim(coalesce(p_customer_message, '')), ''), now(), p_idempotency_key
  )
  returning orders.order_id into v_order_id;

  if p_idempotency_key is not null then
    insert into public.checkout_idempotency_keys(idempotency_key, user_id, order_id)
    values (p_idempotency_key::text, p_user_id, v_order_id);
  end if;

  insert into public.order_status_history(order_id, old_status, new_status, changed_by_user_id, note)
  values (v_order_id, null, 'PLACED', null, 'Comandă plasată de client.');

  insert into public.order_items(order_id, product_id, sku, product_name, quantity, unit_price, line_total, currency_code)
  select v_order_id, rp.product_id, rp.sku, rp.product_name, rp.quantity, rp.unit_price, rp.line_total, rp.currency_code
  from checkout_rpc_products rp
  order by rp.product_id;

  insert into public.payments(order_id, payment_method, status, amount, currency_code, provider_name, provider_payload)
  values (v_order_id, p_payment_method, 'PENDING', v_total_amount, v_currency, upper(v_delivery_method), jsonb_build_object('deliveryMethod', v_delivery_method));

  insert into public.inventory_movements(product_id, movement_type, quantity, note, created_by_admin_id)
  select rp.product_id, 'OUT', rp.quantity, 'Checkout order ' || v_order_number, null
  from checkout_rpc_products rp
  order by rp.product_id;

  update public.products p
  set status = 'OUT_OF_STOCK'
  from checkout_rpc_products rp
  where p.product_id = rp.product_id
    and p.stock_quantity = 0
    and p.status = 'ACTIVE';

  update public.carts set status = 'CHECKED_OUT' where cart_id = v_cart_id;

  if nullif(btrim(coalesce(p_customer_message, '')), '') is not null then
    insert into public.support_conversations(user_id, subject, status, order_id, topic)
    values (p_user_id, 'Comandă #' || v_order_number, 'OPEN', v_order_id, 'ORDER')
    returning conversation_id into v_support_conversation_id;

    insert into public.support_messages(conversation_id, sender_user_id, sender_type, message_body, is_read)
    values (v_support_conversation_id, p_user_id, 'USER', nullif(btrim(coalesce(p_customer_message, '')), ''), false);
  end if;

  return query
  select o.order_id, o.order_number, o.status, o.payment_status, o.fulfillment_status, o.total_amount, o.currency_code, o.created_at
  from public.orders o
  where o.order_id = v_order_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- Row-level security and grants
-- ---------------------------------------------------------------------------

alter table public.users enable row level security;
alter table public.roles enable row level security;
alter table public.user_roles enable row level security;
alter table public.sessions enable row level security;
alter table public.auth_logs enable row level security;
alter table public.product_categories enable row level security;
alter table public.products enable row level security;
alter table public.inventory_movements enable row level security;
alter table public.user_addresses enable row level security;
alter table public.carts enable row level security;
alter table public.cart_items enable row level security;
alter table public.checkouts enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.payments enable row level security;
alter table public.order_status_history enable row level security;
alter table public.support_conversations enable row level security;
alter table public.support_messages enable row level security;
alter table public.events enable row level security;
alter table public.horeca_requests enable row level security;
alter table public.app_rate_limits enable row level security;
alter table public.checkout_idempotency_keys enable row level security;
alter table public.security_events enable row level security;

create policy product_categories_public_read on public.product_categories for select to anon, authenticated using (true);
create policy products_public_read on public.products for select to anon, authenticated using (deleted_at is null and status in ('ACTIVE', 'OUT_OF_STOCK'));
create policy events_public_read on public.events for select to anon, authenticated using (published = true);

create policy users_select_own_or_admin on public.users for select to authenticated using (user_id = public.current_app_user_id() or public.current_app_is_admin());
create policy orders_select_own_or_admin on public.orders for select to authenticated using (user_id = public.current_app_user_id() or public.current_app_is_admin());
create policy carts_select_own_or_admin on public.carts for select to authenticated using (user_id = public.current_app_user_id() or public.current_app_is_admin());
create policy checkouts_select_own_or_admin on public.checkouts for select to authenticated using (user_id = public.current_app_user_id() or public.current_app_is_admin());
create policy user_addresses_select_own_or_admin on public.user_addresses for select to authenticated using (user_id = public.current_app_user_id() or public.current_app_is_admin());
create policy support_conversations_select_own_or_admin on public.support_conversations for select to authenticated using (user_id = public.current_app_user_id() or public.current_app_is_admin());

create policy order_items_select_own_or_admin on public.order_items for select to authenticated using (
  exists (
    select 1 from public.orders o
    where o.order_id = order_items.order_id
      and (o.user_id = public.current_app_user_id() or public.current_app_is_admin())
  )
);

create policy cart_items_select_own_or_admin on public.cart_items for select to authenticated using (
  exists (
    select 1 from public.carts c
    where c.cart_id = cart_items.cart_id
      and (c.user_id = public.current_app_user_id() or public.current_app_is_admin())
  )
);

create policy support_messages_select_own_or_admin on public.support_messages for select to authenticated using (
  exists (
    select 1 from public.support_conversations sc
    where sc.conversation_id = support_messages.conversation_id
      and (sc.user_id = public.current_app_user_id() or public.current_app_is_admin())
  )
);

create policy admins_all_users on public.users to authenticated using (public.current_app_is_admin()) with check (public.current_app_is_admin());
create policy admins_all_roles on public.roles to authenticated using (public.current_app_is_admin()) with check (public.current_app_is_admin());
create policy admins_all_user_roles on public.user_roles to authenticated using (public.current_app_is_admin()) with check (public.current_app_is_admin());
create policy admins_all_sessions on public.sessions to authenticated using (public.current_app_is_admin()) with check (public.current_app_is_admin());
create policy admins_all_products on public.products to authenticated using (public.current_app_is_admin()) with check (public.current_app_is_admin());
create policy admins_all_product_categories on public.product_categories to authenticated using (public.current_app_is_admin()) with check (public.current_app_is_admin());
create policy admins_all_inventory_movements on public.inventory_movements to authenticated using (public.current_app_is_admin()) with check (public.current_app_is_admin());
create policy admins_all_carts on public.carts to authenticated using (public.current_app_is_admin()) with check (public.current_app_is_admin());
create policy admins_all_cart_items on public.cart_items to authenticated using (public.current_app_is_admin()) with check (public.current_app_is_admin());
create policy admins_all_checkouts on public.checkouts to authenticated using (public.current_app_is_admin()) with check (public.current_app_is_admin());
create policy admins_all_orders on public.orders to authenticated using (public.current_app_is_admin()) with check (public.current_app_is_admin());
create policy admins_all_order_items on public.order_items to authenticated using (public.current_app_is_admin()) with check (public.current_app_is_admin());
create policy admins_all_payments on public.payments to authenticated using (public.current_app_is_admin()) with check (public.current_app_is_admin());
create policy admins_all_order_status_history on public.order_status_history to authenticated using (public.current_app_is_admin()) with check (public.current_app_is_admin());
create policy admins_all_support_conversations on public.support_conversations to authenticated using (public.current_app_is_admin()) with check (public.current_app_is_admin());
create policy admins_all_support_messages on public.support_messages to authenticated using (public.current_app_is_admin()) with check (public.current_app_is_admin());
create policy admins_all_events on public.events to authenticated using (public.current_app_is_admin()) with check (public.current_app_is_admin());
create policy admins_all_horeca_requests on public.horeca_requests to authenticated using (public.current_app_is_admin()) with check (public.current_app_is_admin());

revoke all on all tables in schema public from anon, authenticated;
revoke all on all functions in schema public from anon, authenticated;
grant usage on schema public to anon, authenticated, service_role;
grant select on public.product_categories, public.products, public.events to anon, authenticated;
grant all on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;

grant execute on function public.current_app_user_id() to anon, authenticated, service_role;
grant execute on function public.current_app_is_admin() to anon, authenticated, service_role;
grant execute on function public.user_has_role(bigint, public.role_name) to service_role;
grant execute on function public.is_admin(bigint) to service_role;
grant execute on function public.grant_admin_role(bigint) to service_role;
grant execute on function public.revoke_admin_role(bigint) to service_role;
grant execute on function public.resolve_session(text) to service_role;
grant execute on function public.consume_rate_limit(text, integer, integer) to service_role;
grant execute on function public.replace_cart_items(bigint, jsonb) to service_role;
grant execute on function public.support_conversation_summaries(bigint, boolean, text, text, text, integer, integer) to service_role;
grant execute on function public.update_order_admin(bigint, bigint, text, text, text, text) to service_role;
grant execute on function public.place_order(bigint, jsonb, text, text, text, public.payment_method_type, text, text, text, text, text, text, text, uuid) to service_role;

-- ---------------------------------------------------------------------------
-- Minimal seed
-- ---------------------------------------------------------------------------

insert into public.roles(role_name, description)
values
  ('USER', 'Client DeSaga cu Legume'),
  ('ADMIN', 'Administrator DeSaga cu Legume')
on conflict (role_name) do update
set description = excluded.description;

insert into public.product_categories(slug, name, description)
values
  ('legume', 'Legume', 'Legume proaspete, de sezon, de la producători locali.'),
  ('fructe', 'Fructe', 'Fructe proaspete, de sezon, de la producători locali.'),
  ('la-borcan', 'La borcan', 'Bunătăți conservate și produse pregătite la borcan.')
on conflict (slug) do update
set name = excluded.name,
    description = excluded.description;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('images', 'images', true, 5242880, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update
set name = excluded.name,
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

commit;
